# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
# SPDX-License-Identifier: CC0-1.0

name: REUSE
on:
  merge_group:
  push:
    branches: "**"
  pull_request:
    branches: [ main ]
jobs:
  compliance:
    runs-on: ubuntu-24.04
    name: Check for compliance
    steps:
      - name: Checkout last commit
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          persist-credentials: false
      - name: Lint missing copyright and licensing information
        uses: fsfe/reuse-action@211d2700d0242a061dfd6bb1e654004c806f3264
